sudo:
  false

email:
  false

env:
  global:
    - USE_GITHUB_REPOSITORY=yes

language:
  ruby

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1

cache:
  bundler

before_install:
  gem install bundler

script:
  -bundle exec rake coverage
