sudo:
  false

email:
  false

env:
  global:
    - secure: "s0codkWSfqEB71qzc52VmR1USqqNpEu7l3tlvgGDS1OIiCnZgi34mSlV86uwFbgZW50r7SHcEfde6ieOMCxnwgKe6gHu7hME3PRHamwQ79OXqrd68MNMSvu5LQ0KZ01lWJvYF/5FFzr7Si0O2HG4bU7S92f4kUB2ZqWEKG6g6Rl9eQKPzqr6YCLEEUP16KJ2Kev9XvtF8pTOmamVp7/eJ918CULmoCf8YjhSRpV39oBkrvDDowAsM6UBwkOcMIbjmhYO1qAz3/fwL8aeIjDn7uRWJ4MZKhVDtCOrduwR4/7IxMvKJpNw2IFIPpPirKT8wTzn5Hlga22iufaiPlCv3GvsE2vaRby/vtwQsXuk6mDf9ar7EzDlOaFEf0RJ7FGJGEfsFEfza0Bhty9bl8Stiv5XFcoIQCBYwj02Tl8yjmGi1G+KzfY9DLGYjGV17h2s0dSp/dHY40eeIN7ZT/19xhN8aNfJNteqOlhimEKx3bRXQEVGOwksGOPCYu4Xf3qDgNMtcC4AFqBgmWrevXS/iQkip1KYrQg0sKxYlgzOwijRwMRng35RAj9fcN3R/nvKVGsWNZD9pFeBApuayy1LW5FV/ZvVwmw1FT6HGl7Kfiu+EKDo9b0YWlWiA54MnlkcFLxIXhTpW4gv1sar93ylE1QzYled+OR3nIz+TrNsjV0="

language:
  ruby

cache:
  bundler

matrix:
  include:
    - rvm: 2.3.8
    - rvm: 2.4.5
      env: RUBYOPT=--enable-frozen-string-literal USE_FIXED_GEMS=yes
    - rvm: 2.5.5
      env: RUBYOPT=--enable-frozen-string-literal USE_FIXED_GEMS=yes
    - rvm: 2.6.2
      env: RUBYOPT=--enable-frozen-string-literal USE_FIXED_GEMS=yes

before_install:
  - "env -u RUBYOPT gem update --system"
  - "env -u RUBYOPT gem install bundler"

script:
  - bundle exec rake coverage
